# Specify the version of the Docker Compose file format
version: "3"

# Define the services that will be run as part of this Docker Compose configuration
services:
  api:
    build: .
    # Map port 8000 on the host machine to port 8000 on the container
    ports:
      - 8000:8000
    # connect the local directory to the container directory - making it possible to edit the code locally
    volumes:
      - ./:/usr/src/app
    # this makes sure the db service is started before the api service
    depends_on:
      - db
    env_file:
      - ./.env
    # we want that any change in local files should be reflected in the container - so we use the --reload option
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    # this makes sure that when the container is removed, the data is persisted on the host machine
    volumes:
      - postgres_data:/var/lib/postgresql/data

# this is the name of the volume that will be created for db persistence
volumes:
  postgres_data:
